### ISSUE TITLE
Usage example.

### ISSUE THREAD

**Issue by skywinder** [sirlantis/rubocop-for-rubymine#10]
Hello. I installed your plugin, but don't see any difference. How it works?
`rubocop` found 417 offenses.

How to rub it in the project? `inspect code` works the same behaviour. ANd I don't see any no additional options in menu bar.
So, how to make it work?

**Comment by jonnysamps** [comment]
+1

**Comment by skywinder** [comment]
Ok. I got it. There additional highligts appeared in the code. By holding mouse on it you can see hover view with rubocop description of the problem.


![screen shot 2015-03-26 at 22 59 57](https://cloud.githubusercontent.com/assets/3356474/6856926/dd8eece0-d40b-11e4-9270-876a58087567.png)


@sirlantis It would be nice to mention it in readme.

**Comment by jonnysamps** [comment]
@skywinder, I had to manually install the rubocop gem in my project AND add a .rubocop.yml file. What did you do to get it to work?

**Comment by skywinder** [comment]
@jonnysamps sorry for dummy question, but did you install this plugin also (as it described here https://github.com/sirlantis/rubocop-for-rubymine#installation )? If so, then restart RubyMine and it should work. Try to run `rubocop`, and find this cops in RubyMine - they should be highlighted.

**Comment by jonnysamps** [comment]
@skywinder ya, I did exactly that but it didn't work...

**Comment by snowe2010** [comment]
Yeah I also cannot get the plugin to show anything. Before upgrading to the 2.0.0-rc1 release it at least gave me errors.

**Comment by sirlantis** [comment]
Please add the data requested by [CONTRIBUTING](https://github.com/sirlantis/rubocop-for-rubymine/blob/master/CONTRIBUTING.md) to simplify debugging of this issue.

Also read the [Troubleshooting section](https://github.com/sirlantis/rubocop-for-rubymine#troubleshooting) in the README.

**Comment by jonnysamps** [comment]
Those items should probably be in the 'Installation' section IMO.

On Tue, Mar 31, 2015 at 8:02 AM, Marcel Jackwerth <notifications@github.com>
wrote:

> Please add the data requested by CONTRIBUTING
> <https://github.com/sirlantis/rubocop-for-rubymine/blob/master/CONTRIBUTING.md>
> to simplify debugging of this issue.
>
> Also read the Troubleshooting section
> <https://github.com/sirlantis/rubocop-for-rubymine#troubleshooting> in
> the README.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sirlantis/rubocop-for-rubymine/issues/10#issuecomment-88122999>
> .
>



-- 
Jonathan

**Comment by sirlantis** [comment]
@jonnysamps Moved it up there.

**Comment by jonnysamps** [comment]
Great! Thanks!

On Tue, Mar 31, 2015 at 1:06 PM, Marcel Jackwerth <notifications@github.com>
wrote:

> @jonnysamps <https://github.com/jonnysamps> Moved it up there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sirlantis/rubocop-for-rubymine/issues/10#issuecomment-88229287>
> .
>



-- 
Jonathan
