### ISSUE TITLE
Synchronize RuboCop with RubyMine Settings

### ISSUE THREAD

**Issue by whithajess** [sirlantis/rubocop-for-rubymine#13]
Would it be possible to integrate with RubyMine settings to make sure it is following rubocop / the ruby style guide i.e for indenting.

As a side note do you have some good settings for indenting ruby files? As I am having trouble getting 

```
raise APIException.new(
    'test',
    'test'
  )
```

to format automatically as rubocop would suggest

```
raise APIException.new(
  'test',
  'test'
)
```

**Comment by sirlantis** [comment]
This would require some serious reverse engineering of the API. Also I don't think there they are 100% compatible. I recommend that you disable RubyMines linter rules and let RuboCop do the linting - keep the high-level analysis of RubyMine though.
