### ISSUE TITLE
Replace existence-test of `.rubocop.yml` with better check

### ISSUE THREAD

**Issue by andersennl** [sirlantis/rubocop-for-rubymine#14]
Hi, I've followed the setup guide for this plugin but I'm having trouble getting RubyMine to load my `.rubocop.yml`. RubyMine isn't showing any violations. I've used Atom before, which had no trouble finding the rubocop file.

RubyMine shows this hint at the top of some files:
![bildschirmfoto 2015-05-06 um 09 39 27](https://cloud.githubusercontent.com/assets/2667916/7489162/ee9a10e0-f3d3-11e4-856e-445b0923f488.png)

This is what I've found in the generated logs when searching for `rubocop`.
```
2015-05-06 09:17:39,301 [ 131294]   WARN - hub.sirlantis.rubymine.rubocop - Didn't find .rubocop.yml 
2015-05-06 09:17:55,487 [ 147480]   WARN - hub.sirlantis.rubymine.rubocop - Didn't find .rubocop.yml 
2015-05-06 09:18:00,836 [ 152829]   WARN - hub.sirlantis.rubymine.rubocop - Didn't find .rubocop.yml 
2015-05-06 09:18:01,834 [ 153827]   WARN - hub.sirlantis.rubymine.rubocop - Didn't find .rubocop.yml 
```
What am I doing wrong? Thanks!

**Comment by andersennl** [comment]
The initial question has been solved here: https://github.com/sirlantis/rubocop-for-rubymine/issues/7#issuecomment-99384124.

Is it really necessary that I add the rubocop gem to my projects gemfile? Isn't there a way to use a globally installed rubocop gem? Same goes with the `.rubocop.yml`. It would be nice to access the one in the home directory.

**Comment by sirlantis** [comment]
I use this to determine whether Rubocop should be used for this project, otherwise it will highlight every code-base (even those that don't use rubocop as a convention, which causes quite a lot of noise).

I currently don't see a better way, but am open to suggestions.

**Comment by andersennl** [comment]
Ah I see. If it generally is no problem to access a globally installed rubocop gem, maybe a switch in the settings would be possible? Or maybe the rubocop linter could be turned on/off via keyboard shortcuts.

**Comment by tleish** [comment]
So, you use both Gemfile and presence of .rubocop.yml to determine if you should be used for the project?  Why not just use one or the other instead of both?

**Comment by sirlantis** [comment]
These are two different things:
- `.rubocop.yml` is used as an indicator whether the Plugin should do something.
- `Gemfile` will determine whether we invoke `bundle exec rubocop` instead of `rubocop`.

**Comment by tleish** [comment]
For a small project, it seems unnecessary to create a empty ```.rubycop.yml``` just to be able to use ``` rubocop```.  The gem itself doesn't require this to be a part of the project, only if you want to customize it.  What is the purpose for requiring ```.rubycop.yml``` per rubymine project even if there are no rubocop customizations?

**Comment by sirlantis** [comment]
See comment above: https://github.com/sirlantis/rubocop-for-rubymine/issues/14#issuecomment-100176369

**Comment by tleish** [comment]
But, if the rubocop gem is included in the Gemfile for the current project, wouldn't this indicate that rubocop is being used for this project?  Am I missing something?

**Comment by sirlantis** [comment]
I changed the behavior in 3.1.0 to just check whether RubyMine sees the Rubocop gem for the current project (i.e should work for RVM/rbenv/global installs).
