### ISSUE TITLE
In Intellij IDEA 15 the highlighted issues too hard to see

### ISSUE THREAD

**Issue by dec1** [sirlantis/rubocop-for-rubymine#27]
The color for the highlighted issues (ie the underline "squiggle" in the IDE editor) is so faint that its almost impossible to see.
It also seems not possible to change it via File-Settings-Editor-Inspections (changing the color on the swatch there seems to have no effect)

**Comment by sirlantis** [comment]
The plugin uses IntelliJ's [severity highlights](https://github.com/sirlantis/rubocop-for-rubymine/blob/05e2bd701c3ee524adfa8d761d29bd4dfeb2e984/src/io/github/sirlantis/rubymine/rubocop/RubocopAnnotator.kt#L113-L122) - if changing the color of that in the Settings doesn't have an effect, you should file a bug against IntelliJ.

Alternatively you can change the severity of Rubocop's warnings in the `.rubocop.yml` to maybe make them more visible.

**Comment by dec1** [comment]
![intellij-rubocop2](https://cloud.githubusercontent.com/assets/5962877/11625863/5d10e0cc-9cde-11e5-9322-f431fd419dd4.png)

```

Line #3 – convention: Class has too many lines. [189/100]

class ProductSynchronizationController < ApplicationController

Line #3 – convention: Missing top-level class documentation comment.

class ProductSynchronizationController < ApplicationController

Line #4 – convention: Assignment Branch Condition size for start_product_sync is too high. [76.16/15]

  def start_product_sync

Line #4 – convention: Method has too many lines. [66/10]

  def start_product_sync

Line #5 – convention: Do not use Time.now without zone. Use one of Time.zone.now, Time.now.current, Time.now.in_time_zone, Time.now.utc, Time.now.getlocal, Time.now.iso8601, Time.now.jisx0301, Time.now.rfc3339, Time.now.to_i, Time.now.to_f instead.

    start_time = Time.now

```
The above "highlights" for example are pretty much impossible to see. 
I cant see anwhere in the Intellij IDEA settings where I can change the display to somethng more visible.

Am I missing something?
![intellij-rubocop3](https://cloud.githubusercontent.com/assets/5962877/11625891/b4d2c974-9cde-11e5-8c4f-63d9398d072b.png)

**Comment by sirlantis** [comment]
The Rubocop inspection isn't used internally - haven't cleaned that up yet.

Go to: `Editor > Colors & Font > General`, there `Errors and Warnings`. Fix the color for `Weak Warning`.

**Comment by dmoran-epages** [comment]
Thanks for the reply and suggestion.
But following it would affect the display of such warnings in IDEA in general..not just the rubocop ones right?
What do you mean by "The Rubocop inspection isn't used internally"
Thanks in Advance

**Comment by sirlantis** [comment]
The Rubocop uses the IDEA-Warnings. Rubocops `Convention` issues are displayed as `Weak Warning`.

The 'Rubocop' inspection you see in the screenshot is a relic. The plugin defaults to the standard IDEA colors and doesn't use the color/entry that is displayed in the screenshot.
