### ISSUE TITLE
Can JRuby be supported?

### ISSUE THREAD

**Issue by olleolleolle** [sirlantis/rubocop-for-rubymine#5]
<3 this project, a very nice, worked-through add-on.

Looking at this line, it seems that RUBY_SDK is not the same as a JRuby.

https://github.com/sirlantis/rubocop-for-rubymine/blob/5e3670677e0ab8462bb29e404ad120d661e3155c/src/io/github/sirlantis/rubymine/rubocop/RubocopTask.kt#L225

**Comment by sirlantis** [comment]
Can you somehow find out what String is reported for JRuby? I can't find any information from IntelliJ.

**Comment by olleolleolle** [comment]
Dumb answer, probably unrelated: In JRuby, all I know is that, `RUBY_PLATFORM == 'java'`.

**Comment by olleolleolle** [comment]
Hooray!

**Comment by sirlantis** [comment]
Would be happy if you could verify this (3.0.0 required) - worked on my system but you know how it is... ;)

**Comment by olleolleolle** [comment]
You have yet to tag the 3.0.0 release, is that right?

**Comment by olleolleolle** [comment]
Oh, I found it!
